from ui.actions.sources import (
    csv,
    html,
    json,
    re,
    time,
    datetime,
    BytesIO,
    StringIO,
    Path,
    st,
    components,
    Document,
    WD_ALIGN_PARAGRAPH,
    DocxInches,
    DocxPt,
    Workbook,
    Alignment,
    Border,
    Font,
    PatternFill,
    Side,
    Presentation,
    PptxInches,
    PptxPt,
    colors,
    letter,
    ParagraphStyle,
    getSampleStyleSheet,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    clean_preview_text,
    deduplicate_sources,
    make_static_file_link,
    normalize_source_item,
    SIDEBAR_SOURCES_KEY,
    SOURCE_PREVIEW_LIMIT,
    EXPORT_TIMESTAMP_FORMAT,
    PENDING_EXPORT_REQUEST_KEY,
    READY_EXPORT_FILE_KEY,
    EXPORT_FRONTEND_FLUSH_SECONDS,
    ACTION_DEBUG_FILE,
    append_action_debug,
    EXPORT_TYPES,
    safe_html,
    copy_button,
    get_export_timestamp,
    title_case_words,
    make_response_title,
    make_filename_slug,
    make_export_filename,
    get_question_for_message,
    normalize_answer_text,
    is_bullet_line,
    is_numbered_line,
    strip_list_marker,
    split_answer_lines,
    get_source_entries,
    format_source_line,
    build_export_text,
    export_txt,
    export_md,
    export_csv,
    export_xlsx,
    export_xls,
    add_docx_paragraph,
    export_docx,
    get_pdf_styles,
    add_pdf_answer_lines,
    export_pdf,
    split_text_for_slides,
    export_pptx,
    export_ppt,
    get_export_file,
    toggle_export_panel,
    clear_export_runtime_state,
    queue_export_request,
    get_pending_export_request,
    get_ready_export_file,
    display_export_loading,
    prepare_pending_export,
    display_ready_export,
    display_export_buttons,
    prepare_sources_for_drawer,
    get_optional_source_url,
    build_source_card_html,
    render_source_cards_html,
    show_sources_in_sidebar,
    display_sources_button,
)



def display_actions(answer, sources, message_index=None):
    # Copy and export buttons below one assistant answer.
    # Sources are already shown in the left sidebar, so no source button is needed here.
    if st.session_state.get("hide_actions", False) or st.session_state.get("is_generating", False):
        return

    unique_key = str(0 if message_index is None else message_index)
    export_title = make_response_title(get_question_for_message(message_index))

    # Do not update session_state while rendering action rows.
    # chat_ui.py already stores latest sources after generation/history load.

    with st.container(key=f"action_area_{unique_key}"):
        col1, col2, col3 = st.columns([1, 1, 13], gap="small")

        with col1:
            copy_button(answer, key=f"copy_{unique_key}")

        with col2:
            st.button(
                "⇩",
                key=f"export_toggle_{unique_key}",
                help="Download response",
                on_click=toggle_export_panel,
                args=(unique_key,),
            )

        if st.session_state.get("open_export_panel_key") == unique_key:
            with col3:
                with st.container(key=f"export_inline_panel_{unique_key}"):
                    display_export_buttons(answer, sources, unique_key, title=export_title)


# Public names exported by this compatibility/refactor module.
__all__ = [
    'csv',
    'html',
    'json',
    're',
    'time',
    'datetime',
    'BytesIO',
    'StringIO',
    'Path',
    'st',
    'components',
    'Document',
    'WD_ALIGN_PARAGRAPH',
    'DocxInches',
    'DocxPt',
    'Workbook',
    'Alignment',
    'Border',
    'Font',
    'PatternFill',
    'Side',
    'Presentation',
    'PptxInches',
    'PptxPt',
    'colors',
    'letter',
    'ParagraphStyle',
    'getSampleStyleSheet',
    'Paragraph',
    'SimpleDocTemplate',
    'Spacer',
    'clean_preview_text',
    'deduplicate_sources',
    'make_static_file_link',
    'normalize_source_item',
    'SIDEBAR_SOURCES_KEY',
    'SOURCE_PREVIEW_LIMIT',
    'EXPORT_TIMESTAMP_FORMAT',
    'PENDING_EXPORT_REQUEST_KEY',
    'READY_EXPORT_FILE_KEY',
    'EXPORT_FRONTEND_FLUSH_SECONDS',
    'ACTION_DEBUG_FILE',
    'append_action_debug',
    'EXPORT_TYPES',
    'safe_html',
    'copy_button',
    'get_export_timestamp',
    'title_case_words',
    'make_response_title',
    'make_filename_slug',
    'make_export_filename',
    'get_question_for_message',
    'normalize_answer_text',
    'is_bullet_line',
    'is_numbered_line',
    'strip_list_marker',
    'split_answer_lines',
    'get_source_entries',
    'format_source_line',
    'build_export_text',
    'export_txt',
    'export_md',
    'export_csv',
    'export_xlsx',
    'export_xls',
    'add_docx_paragraph',
    'export_docx',
    'get_pdf_styles',
    'add_pdf_answer_lines',
    'export_pdf',
    'split_text_for_slides',
    'export_pptx',
    'export_ppt',
    'get_export_file',
    'toggle_export_panel',
    'clear_export_runtime_state',
    'queue_export_request',
    'get_pending_export_request',
    'get_ready_export_file',
    'display_export_loading',
    'prepare_pending_export',
    'display_ready_export',
    'display_export_buttons',
    'prepare_sources_for_drawer',
    'get_optional_source_url',
    'build_source_card_html',
    'render_source_cards_html',
    'show_sources_in_sidebar',
    'display_sources_button',
    'display_actions',
]
